### ISSUE TITLE
RPG Maker demo error

### ISSUE THREAD

**Issue by Y0oMu** [OpenDFM/ibsen#3]
错误信息：Error: Failed to initialize graphics.
    at SceneManager.initGraphics (rmmz_managers.js:1909:15)
    at SceneManager.initialize (rmmz_managers.js:1881:10)
    at SceneManager.run (rmmz_managers.js:1870:14)
    at Main.onEffekseerLoad (:9091/js/main.js:141:22)
    at Object._onRuntimeInitialized [as onRuntimeInitialized] (effekseer.min.js:33:151)
    at doRun (effekseer.min.js:15:147103)
    at run (effekseer.min.js:15:147294)
    at runCaller (effekseer.min.js:15:146228)
    at removeRunDependency (effekseer.min.js:15:12022)
    at receiveInstance (effekseer.min.js:15:13398) (index):14 Uncaught ReferenceError: require is not defined
    at (index):14:28
![image](https://github.com/user-attachments/assets/30af7186-dae5-4bab-b1a1-7ae41a2461d5)

**Comment by cnlnpjhsy** [comment]
require is not defined可能是没有安装Node.js导致的，可以在安装好之后再试试看吗

**Comment by Y0oMu** [comment]
最后换edge解决了
